version: "3"

services:        
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  dynamodb:
    image: instructure/dynamo-local-admin
    container_name: dynamodb
    ports:
      - "8010:8010"