server:
  port: 8080
spring:
  application:
    name: "producer"
  devtools:
    add-properties: false
  profiles:
    include: local
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true

